---
name: Algorithm-VectorClocks
version: 0.0.1
author:
  - 'Takeru INOUE <takeru.inoue _ gmail.com>'
abstract: Generating a partial ordering of events in a distributed system
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  JSON::Any: 0
  List::MoreUtils: 0
  List::Util: 0
  Perl6::Export::Attrs: 0
  Sys::Hostname: 0
  version: 0
build_requires:
  Test::More: 0
  Test::Perl::Critic: 0
provides:
  Algorithm::VectorClocks:
    file: lib/Algorithm/VectorClocks.pm
    version: 0.0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
